access_log:
  key1:
    aa: something else here
    b: qqqq
    qwe: some->bread->crumb
  stored_proc: getsomething
  uses:
    qwe: asd
reporting:
  stored_proc: reportingsp
  uses:
    cost: 200
    price: 10
